"use client";
import { useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { PageLead,Panel,SectionHead,StatePill } from "@/components/ui";
import type { OutletIntegrationRow } from "@/lib/integration-vault";

type Outlet={id:string;code:string;name:string;city:string;status:string};
const providers=[['pos','POS / ERP'],['swiggy','Swiggy'],['zomato','Zomato'],['google_business','Google Business'],['accounting','Accounting'],['whatsapp','WhatsApp / Messaging'],['custom','Custom API']] as const;
const state=(s:string)=>s==='verified'?'steady':s==='attention'?'critical':s==='disabled'?'info':'watch';
async function req(url:string,init:RequestInit,next='/integrations'){const r=await fetch(url,init);if(r.status===428){location.href=`/security/verify?next=${encodeURIComponent(next)}`;return null}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Action failed');return b}
export function OutletIntegrationVault({outlets,integrations,dedicatedKey}:{outlets:Outlet[];integrations:OutletIntegrationRow[];dedicatedKey:boolean}){
 const router=useRouter();const[selected,setSelected]=useState(outlets[0]?.id||'');const[open,setOpen]=useState(false);const[editing,setEditing]=useState<OutletIntegrationRow|null>(null);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
 const rows=useMemo(()=>integrations.filter(x=>!selected||x.outletId===selected),[integrations,selected]);
 function edit(row?:OutletIntegrationRow){setEditing(row||null);setMsg('');setOpen(true)}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg('');const f=new FormData(e.currentTarget);const credentials:Object=Object.fromEntries(['apiKey','apiSecret','accessToken','accountId'].map(k=>[k,String(f.get(k)||'').trim()]).filter(([,v])=>v));const payload={id:editing?.id,outletId:String(f.get('outletId')),providerKey:editing?.providerKey||String(f.get('providerKey')||'pos'),providerLabel:String(f.get('providerLabel')),baseUrl:String(f.get('baseUrl')||''),credentials:Object.keys(credentials).length?credentials:undefined,status:editing?.status};try{await req('/api/integrations/outlets',{method:editing?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});setOpen(false);router.refresh()}catch(e){setMsg(e instanceof Error?e.message:'Save failed')}finally{setBusy(false)}}
 async function verify(row:OutletIntegrationRow){setBusy(true);try{const b=await req(`/api/integrations/outlets/${row.id}/test`,{method:'POST'});if(b)alert(b.message);router.refresh()}catch(e){alert(e instanceof Error?e.message:'Verification failed')}finally{setBusy(false)}}
 const verified=integrations.filter(x=>x.status==='verified').length,attention=integrations.filter(x=>x.status==='attention').length;
 return <><PageLead code="22" eyebrow="SYSTEM / OUTLET INTEGRATION VAULT" title="Add a new outlet. Plug in its APIs. Keep the secrets out of the interface." copy="Store outlet-specific POS, aggregator, accounting, Google and custom API credentials in an encrypted Owner-only vault. Values are never returned to the browser after save." action={<button className="command-button" onClick={()=>edit()}>ADD INTEGRATION <span>→</span></button>} meta={<><span>{integrations.length} CONFIGURED</span><span>{verified} VERIFIED</span><span>{attention} ATTENTION</span></>}/>
 <div className="summary-ribbon"><span><small>OUTLETS</small><strong>{outlets.length}</strong></span><span><small>INTEGRATIONS</small><strong>{integrations.length}</strong></span><span><small>VERIFIED</small><strong>{verified}</strong></span><span><small>ATTENTION</small><strong>{attention}</strong></span><span><small>VAULT KEY</small><strong>{dedicatedKey?'DEDICATED':'DERIVED'}</strong></span></div>
 <div className="two-column command-gap vault-grid"><Panel><SectionHead no="01" kicker="OUTLET SELECTOR" title="Integration coverage" right={<select className="vault-select" value={selected} onChange={e=>setSelected(e.target.value)}>{outlets.map(o=><option key={o.id} value={o.id}>{o.code} · {o.name}</option>)}</select>}/><div className="vault-list">{rows.length?rows.map(r=><div className="vault-row" key={r.id}><div><strong>{r.providerLabel}</strong><small>{r.outletCode} · {r.credentialFields.join(' / ')||'NO FIELDS'}{r.baseUrl?` · ${r.baseUrl}`:''}</small></div><StatePill state={state(r.status) as any}>{r.status.toUpperCase()}</StatePill><span><small>LAST CHECK</small><b>{r.lastTestedAt?new Date(r.lastTestedAt).toLocaleString('en-IN'):'NOT TESTED'}</b></span><button onClick={()=>verify(r)} disabled={busy}>VERIFY VAULT</button><button onClick={()=>edit(r)}>MANAGE</button></div>):<p className="vault-empty">No integrations configured for this outlet.</p>}</div></Panel>
 <Panel tone="cream"><SectionHead no="02" kicker="SECURITY MODEL" title="How credentials are handled"/><div className="vault-policy"><p><b>Encrypted at rest.</b> AES-256-GCM is applied before credentials reach the database.</p><p><b>Masked by design.</b> The browser receives field names and status only, never stored values.</p><p><b>Fresh Owner MFA.</b> Adding, replacing or verifying credentials requires recent sensitive-action MFA.</p><p><b>Connector-ready.</b> Provider-specific sync jobs can decrypt credentials only server-side when we add each integration.</p></div></Panel></div>
 {open&&<div className="record-modal" role="dialog" aria-modal="true"><div className="record-modal__card"><header><div><small>OUTLET INTEGRATION</small><h2>{editing?'Manage integration':'Add integration'}</h2></div><button onClick={()=>setOpen(false)}>×</button></header><form className="record-form" onSubmit={save}><div className="record-form__split"><label><span>OUTLET</span><select name="outletId" defaultValue={editing?.outletId||selected} required>{outlets.map(o=><option key={o.id} value={o.id}>{o.code} · {o.name}</option>)}</select></label><label><span>PROVIDER</span><select name="providerKey" defaultValue={editing?.providerKey||'pos'} disabled={Boolean(editing)}>{providers.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label></div><label><span>DISPLAY NAME</span><input name="providerLabel" defaultValue={editing?.providerLabel||'POS / ERP'} required/></label><label><span>BASE URL (OPTIONAL)</span><input name="baseUrl" defaultValue={editing?.baseUrl||''} placeholder="https://api.provider.com"/></label><div className="record-form__split"><label><span>API KEY</span><input name="apiKey" type="password" autoComplete="new-password" placeholder={editing?'Leave blank to keep stored value':'Paste API key'}/></label><label><span>API SECRET</span><input name="apiSecret" type="password" autoComplete="new-password" placeholder="Optional"/></label><label><span>ACCESS TOKEN</span><input name="accessToken" type="password" autoComplete="new-password" placeholder="Optional"/></label><label><span>ACCOUNT / MERCHANT ID</span><input name="accountId" autoComplete="off" placeholder="Optional"/></label></div>{msg&&<div className="record-message">{msg}</div>}<footer className="vault-form-foot"><small>Stored values cannot be revealed later. Replace them by entering new values.</small><button className="command-button" disabled={busy}>{busy?'SAVING…':'SAVE SECURELY'} <span>→</span></button></footer></form></div></div>}</>;
}
